# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
archive:
  replacements:
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
nfpm:
  homepage: https://github.com/stepin/udp-sniffer
  description: UDP COM port Sniffer/Proxy is used for debugging communication between apps and devices.
  formats:
    - deb
    - rpm
  bindir: /usr/bin
  license: MIT
  files:
    "LICENSE.txt": "/usr/share/doc/udp-sniffer/LICENSE.txt"
    "README.md": "/usr/share/doc/udp-sniffer/README.md"
    "README.ru.md": "/usr/share/doc/udp-sniffer/README.ru.md"
dockers:
  - image_templates:
      - "stepin/udp-sniffer:{{ .Tag }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
