#!/usr/bin/env bash
set -eu -o pipefail
cd "$(dirname "$0")"
[[ "${TRACE:-}" ]] && set -x

go fmt
go vet
go test ./...
golint ./...
gocyclo -over 25 .
interfacer ./...
find . -name '*.go' | xargs grep -inHwE '(FIXME|TODO|HACK|XXX|BUG)' || true
errcheck ./...
golangci-lint run
